sudo: false
language: php
php:
  - 7.2
  - 7.3
before_script:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 --extensions=php src/ tests/
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
